### PR TITLE
Update OOPSLA.md

### PR DESCRIPTION
**Pull request by potanin**
Added 2024 link and two "how to" document links.

### CODE REVIEW

**Review by andrewcmyers — APPROVED** [review]
Thanks!

**Comment by andrewcmyers** [comment]
There is also a file `Conferences/SPLASH.md` that probably should have a link to the SPLASH howto.

**Comment by sampsyo** [comment]
Thanks, @potanin!

I don't seem to have access to either document. Did you intend to make them world-readable?

We could also consider taking the text from Google Docs and turning them into plain text here on this website, which might help make them maintainable by future SPLASH/OOPSLA chairs.

**Comment by potanin** [comment]
We are currently under active discussion how to separate *private* from *public* info in those documents properly before integrating them further. If you request access to Google Doc, I will approve it and once we figure out how to split up private versus public, this can all be updated. :) Thanks, Alex.

**Comment by sampsyo** [comment]
That sounds good… do you want to include text on the page to mention that these are intentionally not accessible yet? (Otherwise I can imagine you might get a lot of Google Docs requests.)

**Comment by potanin** [comment]
Yes will edit once I get a bit of time today. Thanks!

**Comment by potanin** [comment]
Is this better now? I will figure out a better place once I can see how to split "private" versus "public" info nicely.

**Comment by sampsyo** [comment]
Looks OK! Please get back in touch when you have more thoughts about what to publish on the website versus what to just pass down from chair to chair…

**Pull request merged**
