### PR TITLE
Update the outdated author instructions in Sect. LaTeX class, ...

### PR DESCRIPTION
**Pull request by dbeyer**
- Remove all links to outdated (and unnecessary) files
- Directly mention LaTeX options to be used

### CODE REVIEW

**Comment by dbeyer** [comment]
Good point.  But I moved that to a new issue, for which I will create a new PR. (Since it is orthogonal to the LaTeX discussion.)

**Comment by bcpierce00** [comment]
Looks great to me too.

Harry, please merge when ready.

**Comment by bcpierce00** [comment]
(When you're ready, that is -- I think the PR is ready now.)

**Comment by harrygxu** [comment]
Merged.

**Pull request merged**
